
import React from 'react';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { ScrollArea } from "@/components/ui/scroll-area";

interface BillItem {
  id: string;
  name: string;
  price: string;
  discount: string;
  discountedPrice: number;
}

interface PrintableTableProps {
  items: BillItem[];
  totalPrice: number;
  finalPrice: string;
  discountPercentage: number;
}

export const PrintableTable = React.forwardRef<HTMLDivElement, PrintableTableProps>(
  ({ items, totalPrice, finalPrice, discountPercentage }, ref) => {
    const formatToRupiah = (amount: number | string) => {
      const number = typeof amount === 'string' ? parseFloat(amount) : amount;
      return new Intl.NumberFormat('id-ID', {
        style: 'currency',
        currency: 'IDR',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0,
      }).format(number);
    };

    return (
      <div 
        ref={ref} 
        className="p-8 bg-white relative"
        style={{ 
          width: '800px',
          height: '600px',
          boxSizing: 'border-box',
          overflow: 'hidden', // Changed from 'auto' to 'hidden' to prevent scrollbars
          pageBreakInside: 'avoid',
          pageBreakAfter: 'always',
        }}
      >
        <div className="flex items-center justify-center mb-6">
          <img 
            src="/lovable-uploads/0af8fa0e-21f6-4556-9fa4-13109f978c76.png" 
            alt="Fourier Project Logo" 
            className="h-16 w-16 mr-3"
          />
          <h2 className="text-2xl font-bold">Bill Details</h2>
        </div>

        <div style={{ width: '100%', overflow: 'hidden' }}>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Item Name</TableHead>
                <TableHead>Original Price</TableHead>
                <TableHead>Discount</TableHead>
                <TableHead>Final Price</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {items.map((item) => (
                <TableRow key={item.id}>
                  <TableCell>{item.name}</TableCell>
                  <TableCell>{formatToRupiah(item.price)}</TableCell>
                  <TableCell>{formatToRupiah(item.discount)}</TableCell>
                  <TableCell>{formatToRupiah(item.discountedPrice)}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>

        <div className="mt-4 text-right">
          <p className="font-semibold">Total Price: {formatToRupiah(totalPrice)}</p>
          <p className="font-semibold">Final Price: {formatToRupiah(finalPrice)}</p>
          <p className="font-semibold">Discount: {discountPercentage}%</p>
        </div>

        <div className="absolute inset-0 flex items-center justify-center pointer-events-none opacity-10 rotate-[-30deg]">
          <div className="text-center">
            <img 
              src="/lovable-uploads/0af8fa0e-21f6-4556-9fa4-13109f978c76.png" 
              alt="Watermark" 
              className="w-32 h-32 mx-auto mb-4"
            />
            <p className="text-3xl font-bold">Generated by Fourier Project</p>
          </div>
        </div>
      </div>
    );
  }
);

PrintableTable.displayName = 'PrintableTable';
