// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cggzobbpnbjdoanmxxds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnZ3pvYmJwbmJqZG9hbm14eGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyOTMwODcsImV4cCI6MjA2MDg2OTA4N30.555F3GBN1diYmG0FkdY2Z47OsPuuasB8Tn6-Am2-1v8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);